name: Python Bindings

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Build on Rust stable
        run: cargo build --color always --all-targets --features _danger-local-https
      - name: Install Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install python-bitcoinlib
      - name: Generate bindings on Linux
        run: cd python && bash generate_linux.sh
      # TODO generate other bindings
      # TODO run unit and int. tests
